<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Regression Suite" duration-ms="89" started-at="2019-01-05T07:08:22Z" finished-at="2019-01-05T07:08:22Z">
    <groups>
      <group name="regression">
        <method signature="AssertionsTest.test1()[pri:0, instance:testng.AssertionsTest@5034c75a]" name="test1" class="testng.AssertionsTest"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="AssertionsTest.test1()[pri:0, instance:testng.AssertionsTest@5034c75a]" name="test1" class="testng.AssertionsTest"/>
      </group> <!-- smoke -->
    </groups>
    <test name="Test" duration-ms="89" started-at="2019-01-05T07:08:22Z" finished-at="2019-01-05T07:08:22Z">
      <class name="testng.AssertionsTest">
        <test-method status="PASS" signature="test1()[pri:0, instance:testng.AssertionsTest@5034c75a]" name="test1" duration-ms="19" started-at="2019-01-05T02:08:22Z" finished-at="2019-01-05T02:08:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="test5()[pri:0, instance:testng.AssertionsTest@5034c75a]" name="test5" duration-ms="3" started-at="2019-01-05T02:08:22Z" finished-at="2019-01-05T02:08:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5 -->
        <test-method status="FAIL" signature="test6()[pri:0, instance:testng.AssertionsTest@5034c75a]" name="test6" duration-ms="5" started-at="2019-01-05T02:08:22Z" finished-at="2019-01-05T02:08:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [hello] but found [Test]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [hello] but found [Test]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at testng.AssertionsTest.test6(AssertionsTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test6 -->
        <test-method status="PASS" signature="test4()[pri:0, instance:testng.AssertionsTest@5034c75a]" name="test4" duration-ms="3" started-at="2019-01-05T02:08:22Z" depends-on-methods="testng.AssertionsTest.test1" finished-at="2019-01-05T02:08:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method status="SKIP" signature="test7()[pri:0, instance:testng.AssertionsTest@5034c75a]" name="test7" duration-ms="0" started-at="2019-01-05T02:08:22Z" depends-on-methods="testng.AssertionsTest.test6" finished-at="2019-01-05T02:08:22Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AssertionsTest.test7()[pri:0, instance:testng.AssertionsTest@5034c75a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AssertionsTest.test7()[pri:0, instance:testng.AssertionsTest@5034c75a] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test7 -->
        <test-method status="SKIP" signature="test9()[pri:0, instance:testng.AssertionsTest@5034c75a]" name="test9" duration-ms="0" started-at="2019-01-05T02:08:22Z" depends-on-methods="testng.AssertionsTest.test7" finished-at="2019-01-05T02:08:22Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AssertionsTest.test9()[pri:0, instance:testng.AssertionsTest@5034c75a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AssertionsTest.test9()[pri:0, instance:testng.AssertionsTest@5034c75a] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test9 -->
      </class> <!-- testng.AssertionsTest -->
    </test> <!-- Test -->
  </suite> <!-- Regression Suite -->
</testng-results>
